Repository FelipeOrtizDev/FicaFrio, pull requests merged in 2023-11, with the labels that each got.

#2 Adição dos arquivos das paginas
  src/App.jsx
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.jsx
  src/Components/Tarefas/Tarefas.css
  src/Components/Tarefas/Tarefas.jsx
  src/Pages/Cadastro/Cadastro.css
  src/Pages/Cadastro/Cadastro.jsx
  src/Pages/Calendario/Calendario.css
  src/Pages/Calendario/Calendario.jsx
  src/Pages/Login/Login.css
  src/Pages/Login/Login.jsx
  src/Pages/Planos/Planos.css
  src/Pages/Planos/Planos.jsx
  src/Pages/SobreNos/SobreNos.css
  src/Pages/SobreNos/SobreNos.jsx
Labels: documentation, enhancement

#3 Ajuste da API do Chatgpt
  src/App.jsx
  src/Components/Tarefas/OrganizadorTarefas.jsx
  src/Components/Tarefas/Tarefas.css
  src/Components/Tarefas/Tarefas.jsx
  src/Components/TaskCard/TaskCard.css
  src/Components/TaskCard/TaskCard.jsx
  src/Services/APIS/AgendaService.js
  src/Services/APIS/GPT3Services.js
  src/index.css
Labels: documentation, enhancement

#6 Teste Rotas 3(Deu certo)
  src/App.jsx
  src/Components/Layout/Layout.jsx
  src/Components/Navbar/Navbar.jsx
  src/main.jsx
Labels: bug, documentation

#9 Ajuste das rotas e layout da pagina
  src/App.css
  src/App.jsx
  src/Components/Navbar/Nave.css
  src/Components/Navbar/Nave.jsx
  src/Pages/LandinPage/LandinPage.css
  src/Pages/LandinPage/LandinPage.jsx
  src/assets/background.png
  src/assets/peguin.png
  src/index.css
  src/main.jsx
Labels: documentation

#10 Estrutura Footer
  src/App.css
  src/App.jsx
  src/Components/Footer/Footer.jsx
Labels: bug, enhancement

#16 ajuste Footer 2
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Components/Rodape/Rodape.jsx
  src/main.jsx
Labels: documentation, enhancement

#18 Footer css2
  package-lock.json
  package.json
  src/Components/Rodape/Rodape.css
  src/Components/Rodape/Rodape.jsx
Labels: documentation

#19 ajuste footer icones e LandinPage
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Components/Navbar/Nave.css
  src/Components/Navbar/Nave.jsx
  src/Components/Rodape/Rodape.css
  src/Components/Rodape/Rodape.jsx
  src/Pages/LandinPage/LandinPage.css
  src/Pages/LandinPage/LandinPage.jsx
  src/assets/FundoEstresse.png
  src/assets/FundoInterroga.png
  src/assets/FundoPorquinho.png
  src/index.css
Labels: bug, documentation
